"""empty message

Revision ID: 2ce62af2750d
Revises: 
Create Date: 2023-03-12 12:46:14.404218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce62af2750d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propertyType', sa.String(length=80), nullable=True))
        batch_op.drop_column('propertytype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propertytype', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('propertyType')

    # ### end Alembic commands ###
